#!/bin/bash

#!/bin/bash

# Easiest way, as long everything is done just overwrite the file

source ~/scripts/.portergos_utility

_get_size(){

#divide by 3 800x600
# divide by 4 for 1280x768

INSTALL_LOG_FILE="/home/liveuser/portergos-install.log"

width=$(echo $(($(xrandr | grep 'current' | sed -e 's/^.*current//' |awk '{ print $1 }')/3)))
height=$(echo $(($(xrandr | grep 'current' | sed -e 's/^.*current//' -e 's/,.*//' |awk '{ print $3 }')/3)))

}

_online(){

sudo cp -praf /usr/share/calamares/settings.conf_vanilla /usr/share/calamares/settings.conf
sudo cp -praf /usr/share/calamares/modules/packages.conf_online /usr/share/calamares/modules/packages.conf
sudo cp -praf /usr/share/calamares/modules/welcome.conf_online /usr/share/calamares/modules/welcome.conf

}

_offline(){

sudo cp -praf /usr/share/calamares/settings.conf_offline /usr/share/calamares/settings.conf
sudo cp -praf /usr/share/calamares/modules/packages.conf_offline /usr/share/calamares/modules/packages.conf
sudo cp -praf /usr/share/calamares/modules/welcome.conf_offline /usr/share/calamares/modules/welcome.conf

}

_cli(){
$TERMINAL -e sh -c "sudo /offline_installer/installer"

}

run_calamares(){
touch $INSTALL_LOG_FILE 
cat <<EOF > $INSTALL_LOG_FILE
############## $INSTALL_LOG_FILE
############## UTC: $(date -u "+%Y-%m-%d %H:%M")
EOF
sh -c "pkexec /usr/bin/calamares -d >> /home/liveuser/portergos-install.log" &
tilix -e "watch -tn1 tail $INSTALL_LOG_FILE"

#find * -type d -empty
# PACMAN_LOG="$(/usr/bin/ls -1 /tmp/calamares-root-*/var/log/pacman.log 2>/dev/null | tail -n 1)"
#local INSTALL_LOG_FILE=./postergos-install.log

cat /home/liveuser/portergos-install.log | curl -F 'f:1=<-' ix.io

}
_choose_method(){

ANSWER=$(yad --width="$width" --height="$height" --center --on-top --title="Please choose an option for installation" --list --separator="" --column="Install Portergos" "CLI installer (Offline)" "Calamares Online (choose desktop - Arch vanilla)" "Calamares Offline")

    if [[ $ANSWER == "CLI installer (Offline)" ]]; then _cli; fi
    if [[ $ANSWER == "Calamares Offline" ]]; then _offline; run_calamares; fi
    if [[ $ANSWER == "Calamares Online (choose desktop - Arch vanilla)" ]]; then _online; run_calamares; fi

}

# STARTS HERE
_get_size
_choose_method
